### PR TITLE
fix: missing dependency change-case

### PR DESCRIPTION
**Pull request by dryajov**
Adding missing dependency `change-case`

### CODE REVIEW

**Comment by meirgottlieb** [comment]
hey, thanks for the patch but I already fixed this if you pull down the latest.

**Comment by meirgottlieb** [comment]
Opps. My mistake. I merged it.

**Comment by dryajov** [comment]
ah, sorry! Missed you're fix then 👍

**Comment by meirgottlieb** [comment]
FYI just published to NPM as 1.7.2

**Comment by dryajov** [comment]
:+1

**Pull request merged**
